<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Language Lines for the Profile Page.
    |--------------------------------------------------------------------------
    */

    'sub_heading' => 'Change information about yourself on this page.',
    'personal_info' => 'Personal Information',
    'firstname' => 'First Name',
    'firstname_placeholder' => 'Enter your first name',
    'lastname' => 'Last Name',
    'lastname_placeholder' => 'Enter your last name',
    'email' => 'Email Address', 
    'email_placeholder' => 'Enter your email address',
    'email_info' => 'Email Address cannot be changed by the user for security reasons. Reach out to our customer support team if you really need to change your Email Address on this account.',
    'country' => 'Country',
    'phone' => 'Phone #',
    'phone_info' => 'Your Phone Number will be used for verification in case you loose access to your account.',
    'dob' => 'Date of Birth',
    'billing_info' => 'Billing Information',
    'address1' => 'Address Line 1',
    'address1_placeholder' => 'Your Apt/Suit/Building #',
    'address2' => 'Address Line 2',
    'address2_placeholder' => 'Street/Locality/Landmark Name.',
    'city' => 'City',
    'city_placeholder' => 'Enter your City Name',
    'zipcode' => 'Zipcode', 
    'zipcode_placeholder' => 'Enter your area zipcode/pincode',
    'state' => 'State',
    'account_info' => 'Account Information',
    'randomizer' => 'Password Randomizer / Generator',
    'randomizer_info' => 'Select the difficulty/complexity level of our Random Password/String Generator.',
    'support_pin' => 'Support PIN',
    'support_pin_info' => 'This 4-digit support pin is used by our support staff to verify your identity when contacting us.',
    'support_pin_placeholder' => 'Your 4-digit Support PIN',
    'complete_my_profile' => 'Complete My Profile',
    'change_avatar_btn' => 'Change Avatar',
    'change_avatar_head' => 'Change your Avatar',
    'update_profile' => 'Update Profile',
    'change_avatar' => 'Change Avatar',
    'change_pass_btn' => 'Change Master Password',
    'change_pass_head' => 'Change your master password',
    'current_pass' => 'Current Password',
    'current_pass_placeholder' => 'Your current master password',
    'otp_info' => 'Enter the one-time-password from the Authenticator App',
    'new_pass' => 'New Master Password',
    'new_pass_placeholder' => 'Enter your new master password',
    'new_pass_confirm' => 'Confirm New Master Password',
    'new_pass_confirm_placeholder' => 'Confirm your new master password',
    'view_ip_logs' => 'View IP Logs',
    'delete_account_btn' => 'Delete My Account',
    'delete_account_head' => 'Do your really want to Delete your account',
    'delete_account_body' => 'Once confirmed, your account will be marked for deletion and will be permantly deleted along with any associated data after 7-days. This has been done as a precautionary step to prevent accidental deletions. You can always cancel deletion before the 7-day deadline and save your account.',
    'delete_account_confirm' => 'Yes, Confirm Deletion',
    'ip_logs' => 'Login IP Logs',
    'ip_logs_head' => 'My Login IP Logs',
    'ip_logs_sub' => 'You can view all your login ip logs for the past 31 Days here on this page. If you observe anything suspecious, be sure to change your Master Password <a href=":url1">here</a> and activate 2-Step Authentication <a href=":url2">here</a> (if you havent done that already);',
    'view_ip_logs' => 'View IP Logs',
    'delete_on' => 'This account will be permanantly deleted on <span class="badge badge-info">:delete</span>',
    'notifications' => 'Notifications',
    'view_all' => 'View All',
    'mark_read' => 'Mark all as read',
    'no_notifications' => 'No New Notifications',
    'notifications_sub' => 'You can view all of your app notifications below. Mark them as read or even delete them if you like.',
    'notifications_clear' => 'Clear Notifications',
    'request_data_btn' => 'Request Personal Data',
    'request_data_sub' => 'You can request your personal data here. We will create a ZIP and e-mail you a protected link, this ZIP is saved for 1 day on our server and then it will be deleted for your own safety. You can request this personal data export once per day.',
    'oauth_login' => 'This account was created using OAuth from <span class="text-capitalize"><b>:oauth</b></span>.',
    'oauth_login_sub' => 'You can access your account using the <b>"Login with <span class="text-capitalize">:oauth</span>"</b> button on the login page without a password.'
];