<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Language Snippets for Commonly Used Phrases.
    |--------------------------------------------------------------------------
    */

    'verified' => 'Verified',
    'unverified' => 'Unverified',
    'secured' => 'Secured',
    'unsecured' => 'Unsecured',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'disabled' => 'Disabled',
    'enabled' => 'Enabled',
    'locked' => 'Locked',
    'unlocked' => 'Unlocked',
    'available' => 'Available',
    'unavailable' => 'Unavailable',
    'warning' => 'Warning',
    'email_verified' => 'Email Address Verified',
    'email_unverified' => 'Email Address Unverified',
    '2step_secured' => '2-Step Authentication Active',
    '2step_unsecured' => '2-Step Authentication Inactive',
    'vaults' => 'Vaults',
    'folders' => 'Folders', 
    'sites' => 'Sites',
    'vault' => 'Vault',
    'folder' => 'Folder',
    'site' => 'Site',
    'hi_user' => 'Hi, :user',
    'reset_form_btn' => 'Reset Form',
    'vault_pass' => 'Vault Password',
    'vault_pass_confirm' => 'Confirm Vault Password',
    'otp' => 'One Time Passcode',
    'otp_placeholder' => 'Enter your 2-Step Authentication OTP from the Google Authenticator App.',
    'production_warning' => 'Do not modify during production. May cause unintended issues.',
    'date' => 'Date',
    'status' => 'Status',
    'action' => 'Action',
    'actions' => 'Actions',
    'copy' => 'Copy',
    'open' => 'Open',
    'delete' => 'Delete',
    'last_updated' => 'Last Updated',
    'accepts_html' => 'Accepts HTML Syntax for Links & Styling',
    'parses_html' => 'Parses HTML Syntax for Links & Styling Accordingly.',
    'created_at' => 'Created At',
    'updated_at' => 'Updated At',
    'go_back' => 'Go Back',
    'view_docs' => 'View Docs',
    'account' => 'Account',
    'time' => 'Time',
    'ip' => 'IP Address',
    'browser' => 'Browser',
    'platform' => 'Platform',
    'whats_this' => 'Whats this?',
];
