<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Language Lines for a selected Vault Page.
    |--------------------------------------------------------------------------
    */

    'settings' => 'Vault Settings', 
    'lock' => 'Vault Lock',
    'quick_links' => 'Quick Links',
    'folders' => 'Folders',
    'default_vault_name' => 'Personal',
    'default_vault_description' => 'Your default vault for storing items.',
    'add_new_site' => 'Add New Site',
    'create_new_folder' => 'Create New Folder',
    'create_folder_in' => 'Create a New Folder in the <b><u>:vault</u></b> Vault',
    'folder_name' => 'Folder Name',
    'folder_name_placeholder' => 'Enter a name for the Folder',
    'folder_icon' => 'Select an Icon for the Folder',
    'create_folder' => 'Create Folder',
    'add_site_to' => 'Add a New Site to the <b><u>:vault</u></b> Vault',
    'site_name' => 'Site Name / Title',
    'site_name_placeholder' => 'Enter a Name for the Site',
    'site_category' => 'Category',
    'site_category_select' => 'Select a Category for the Site',
    'site_link' => 'URL / Login Link',
    'site_link_placeholder' => 'URL / Login Link of the Site',
    'site_login_id' => 'Login ID / Username',
    'site_login_id_placeholder' => 'Login ID / Username of the Site',
    'site_login_pass' => 'Login Password',
    'site_login_pass_placeholder' => 'Login Password of the Site',
    'generate' => 'Generate',
    'site_login_pass_sub' => 'You can change the complexity of the generated password from your <a href=":profile">profile</a>',
    'site_add_info' => 'Additional Info',
    'site_add_to_folder' => 'Add to a Folder',
    'site_add_to_select' => 'Add the Site to an Existing Folder',
    'add_site' => 'Add Site',
    'quick_view' => 'Quick View',
    'link' => 'URL / Link',
    'login_id' => 'Login ID',
    'login_pass' => 'Login Password',
    'open_site' => 'Open Site Details',
    'fav_this_site' => 'Favorite this Site',
    'fav' => 'Favorited',
    'add_site_to_folder' => 'Click to add this Site to a Folder.',
    'add_site_to_select_folder' => 'Add <b><u>:name</u></b> to a Folder',
    'select_a_folder' => 'Select a Folder',
    'add_to_folder' => 'Add to Folder',
    'add_to_folder_none' => 'This vault does not contain any folders. Create a new folder to get started.',
    'copy' => 'Copy',
    'general_settings' => 'General Settings',
    'general_settings_head' => 'General Settings for <b><u>:vault</u></b> Vault',
    'general_settings_sub' => 'You can adjust all the general settings for this vault here.',
    'general_settings_info' => 'General settings such as, vault name, description, icon, etc.',
    'general_settings_update_btn' => 'Update General Settings',
    'password_settings' => 'Password Settings',
    'password_settings_head' => 'Password Settings for <b><u>:vault</u></b> Vault',
    'password_settings_sub' => 'You can adjust all the password settings here for this vault here.',
    'password_settings_info' => 'Add a Lock to your Vault by setting up a Password.',
    'password_add_btn' => 'Add Password Protection',
    'password_protected' => 'This Vault is Password Protected',
    'current_pass' => 'Current Vault Password',
    'password_remove_btn' => 'Remove Password Protection',
    'delete_vault' => 'Delete Vault',
    'delete_vault_head' => 'Delete <b><u>:vault</u></b> Vault',
    'delete_vault_sub' => 'You can delete the vault and all its related data from this menu.',
    'delete_vault_confirm' => 'I confirm <b>deletion</b> of this Vault. I understand all the related accounts and data will also be deleted permanantly.',
    'delete_vault_btn' => 'Delete This Vault',
    'site_limit' => 'Sorry! Site Limit Reach. You cannot add any more sites.',
    'folder_limit' => 'Sorry! Folder Limit Reach. You cannot create any more folders.',
    'move_title' => 'Move <b><u>:title</u></b> to another Vault',
    'select_vault' => 'Select a Vault',
    'move_btn' => 'Move to Vault',
    'folder' => [
        'name' => ':name Folder',
        'current' => 'Current Folder',
        'delete' => 'Delete This Folder',
        'delete_head' => 'Are you sure you want to delete the <u>:name</u> folder?',
        'confirm' => 'Confirm Deletion',
        'confirm_select' => 'Select Yes if you want to delete this folder',
        'confirm_select_yes' => 'Yes, Delete this Folder',
        'confirm_sites' => 'Delete All the Sites inside this Folder as well?',
        'confirm_sites_select' => 'Select Yes if you want to delete all the sites inside this folder',
        'confirm_sites_yes' => 'Yes, Delete all the Sites aswell',
        'confirm_sites_no' => 'No, Keep the Sites',
        'confirm_sites_help' => 'If you select NO, all the sites will stay intact inside the Vault.',
    ],
];